export const SEARCH_FLIGHTS = 'SEARCH_FLIGHTS';
export const SEARCH_FLIGHTS_SUCCESS = 'SEARCH_FLIGHTS_SUCCESS';
export const SELECT_FLIGHT = 'SELECT_FLIGHT';

export const FETCH_SEATS = 'FETCH_SEATS';
export const FETCH_SEATS_SUCCESS = 'FETCH_SEATS_SUCCESS';
